name: stream img

run-name: "${{ github.actor }} is building 🚀"
on: [ push ]

env:
  "IMAGE": "${{ secrets.AZURE_REGISTRY_ENDPOINT }}/${{ github.repository }}:${{ github.sha }}"
  "LATEST_TAG": "${{ secrets.AZURE_REGISTRY_ENDPOINT }}/${{ github.repository }}:latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  "build":
    name: "Build Image"
    runs-on: "ubuntu-latest"
    steps:
      - run: echo "🔎 Branch name ${{ github.ref }} repository is ${{ github.repository }}."
      - uses: "actions/checkout@v4"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to Azure Container Registry"
        uses: "docker/login-action@v2"
        with:
          "registry": "${{ secrets.AZURE_REGISTRY_ENDPOINT }}"
          "username": "${{ secrets.AZURE_REGISTRY_USERNAME }}"
          "password": "${{ secrets.AZURE_REGISTRY_PASSWORD }}"

      - name: "Build and push the Docker image"
        uses: "docker/build-push-action@v3"
        with:
          context: .
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ${{env.LATEST_TAG }},${{ env.IMAGE }}


      - name: Checkout Deployment Scripts
        uses: politiet/operative-sensorer-update-tag-action@main
        with:
          pat: ${{ secrets.UPDATE_IMAGE_TAG_PAT }}
          service: stream-img
          tag: ${{ github.sha }}
